# Lab 8 TF Manipulation

# Lab 8 TF Manipulation

In [0]:
import tensorflow as tf
import numpy as np

In [0]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)
print(t.ndim) # rank
print(t.shape) # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

[0. 1. 2. 3. 4. 5. 6.]
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


In [0]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t.ndim) # rank
print(t.shape) # shape

2
(4, 3)


In [0]:
t = tf.constant([1,2,3,4])
tf.print(tf.shape(t))

[4]


In [0]:
t = tf.constant([[1,2],
                 [3,4]])
tf.print(tf.shape(t))

[2 2]


In [0]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.print(tf.shape(t))

[1 2 3 4]


In [0]:
matrix1 = tf.constant([[3., 2.]])
matrix2 = tf.constant([[1., 1.]])
tf.print(tf.matmul(matrix1, matrix2))

InvalidArgumentError: ignored

In [0]:
tf.print((matrix1*matrix2))

[[3 2]]


In [0]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
tf.print((matrix1+matrix2))

[[5 5]
 [5 5]]


In [0]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
tf.print((matrix1+matrix2))

[[5 5]]


Reduce Mean/Sum

In [0]:
#integer
tf.print(tf.reduce_mean([1, 2], axis=0))

1


In [0]:
#float
x = [[1., 2.],
     [3., 4.]]


tf.print(tf.reduce_mean(x))

2.5


In [0]:
tf.print(tf.reduce_mean(x, axis=0))

[2 3]


In [0]:
tf.print(tf.reduce_mean(x, axis=1))

[1.5 3.5]


In [0]:
tf.print(tf.reduce_mean(x, axis=-1))

[1.5 3.5]


In [0]:
tf.print(tf.reduce_sum(x))

10


In [0]:
tf.print(tf.reduce_sum(x, axis=0))

[4 6]


In [0]:
tf.print(tf.reduce_sum(x, axis=-1))

[3 7]


In [0]:
tf.print(tf.reduce_mean(tf.reduce_sum(x, axis=-1)))

5


Argmax with axis

In [0]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.print(tf.argmax(x, axis=0))

[1 0 0]


In [0]:
tf.print(tf.argmax(x, axis=1))

[2 0]


In [0]:
tf.print(tf.argmax(x, axis=-1))

[2 0]


Reshape, Squeeze, Expand_dims

In [0]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [0]:
#rank=2, 가장 바깥쪽 shape은 보존(조합 변경X)
tf.print(tf.reshape(t, shape=[-1, 3]))

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [9 10 11]]


In [0]:
#rank=3
tf.print(tf.reshape(t, shape=[-1, 1, 3]))

[[[0 1 2]]

 [[3 4 5]]

 [[6 7 8]]

 [[9 10 11]]]


In [0]:
tf.print(tf.squeeze([[0], [1], [2]]))

[0 1 2]


In [0]:
tf.print(tf.expand_dims([0, 1, 2], 1))

[[0]
 [1]
 [2]]


One hot

In [0]:
tf.print(tf.one_hot([[0], [1], [2], [0]], depth=4))

[[[1 0 0 0]]

 [[0 1 0 0]]

 [[0 0 1 0]]

 [[1 0 0 0]]]


In [0]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.print(tf.reshape(t, shape=[-1, 3]))

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]]


Casting

In [0]:
#integer로 변경
tf.print(tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32))

[1 2 3 4]


In [0]:
#True,False --> 1,0 (accuracy 계산)
tf.print(tf.cast([True, False, 1 == 1, 0 == 1], tf.int32))

[1 0 1 0]


Stack

In [0]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.print(tf.stack([x, y, z]))

[[1 4]
 [2 5]
 [3 6]]


In [0]:
tf.print(tf.stack([x, y, z], axis=1))

[[1 2 3]
 [4 5 6]]


Ones like and Zeros like

In [0]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.print(tf.ones_like(x))

[[1 1 1]
 [1 1 1]]


In [0]:
tf.print(tf.zeros_like(x))

[[0 0 0]
 [0 0 0]]


Zip

In [0]:
#복수 개 tensor 한번에 처리
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [0]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


# Lab 9 XOR

In [0]:
# 3.23 세번째 신경망 네트워크 : XOR
import tensorflow as tf
import numpy as np
x = np.array([[1,1], [1,0], [0,1], [0,0]])
y = np.array([[0], [1], [1], [0]])
w = tf.random.normal([2],0,1)
b = tf.random.normal([1],0,1)
b_x = 1

for i in range(2000):
    error_sum = 0
    for j in range(4):
        output = tf.sigmoid(np.sum(x[j]*w)+b_x*b)
        error = y[j][0] - output
        w = w + x[j] * 0.1 * error
        b = b + b_x * 0.1 * error
        error_sum += abs(error) 
        # if i% 200 == 1:
          # print("output:", output, ", error:", error, ", w:", w, ", b:", b)
        
    if i % 200 == 190:
        print(i, error_sum)
        # for j in range(4):
          # print(j,":",y[j][0],", output: ", output,", w:", w, ", b:", b)

190 tf.Tensor([2.0516434], shape=(1,), dtype=float32)
390 tf.Tensor([2.0512848], shape=(1,), dtype=float32)
590 tf.Tensor([2.051271], shape=(1,), dtype=float32)
790 tf.Tensor([2.0512705], shape=(1,), dtype=float32)
990 tf.Tensor([2.0512705], shape=(1,), dtype=float32)
1190 tf.Tensor([2.0512705], shape=(1,), dtype=float32)
1390 tf.Tensor([2.0512705], shape=(1,), dtype=float32)
1590 tf.Tensor([2.0512705], shape=(1,), dtype=float32)
1790 tf.Tensor([2.0512705], shape=(1,), dtype=float32)
1990 tf.Tensor([2.0512705], shape=(1,), dtype=float32)


In [0]:
# 3.24 XOR 네트워크의 평가
for i in range(4):
    print('X:', x[i], 'Y:', y[i], 'Output:', tf.sigmoid(np.sum(x[i]*w)+b))

X: [1 1] Y: [0] Output: tf.Tensor([0.5128176], shape=(1,), dtype=float32)
X: [1 0] Y: [1] Output: tf.Tensor([0.5128176], shape=(1,), dtype=float32)
X: [0 1] Y: [1] Output: tf.Tensor([0.5], shape=(1,), dtype=float32)
X: [0 0] Y: [0] Output: tf.Tensor([0.5], shape=(1,), dtype=float32)


In [0]:
# 3.25 XOR 네트워크의 w, b 값 확인
#(w1가 크고, b는 거의 영향 X)
tf.print('w:', w)
tf.print('b:', b)

w: [0.0512818806 1.1920929e-07]
b: [-1.52736902e-07]


In [0]:
# 3.26 AND 네트워크의 w, b 값 확인
# w: tf.Tensor([6.9484286 6.951607 ], shape=(2,), dtype=float32)
# b: tf.Tensor([-10.601849], shape=(1,), dtype=float32)

In [0]:
# 3.27 tf.keras 를 이용한 XOR 네트워크 계산
import numpy as np
x = np.array([[1,1], [1,0], [0,1], [0,0]])
y = np.array([[0], [1], [1], [0]])

# tf.sequential (일직선 배치)
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=2, activation='sigmoid', input_shape=(2,)),
    tf.keras.layers.Dense(units=1, activation='sigmoid')
])

model.compile(optimizer=tf.keras.optimizers.SGD(lr=0.3), loss='mse', metrics=['accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 2)                 6         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [0]:
# 3.28 tf.keras 를 이용한 XOR 네트워크 학습
history = model.fit(x, y, epochs=200, batch_size=1)


Epoch 1/200
4/4 [==============================] - 0s 2ms/step - loss: 0.3220 - accuracy: 0.5000
Epoch 2/200
4/4 [==============================] - 0s 1ms/step - loss: 0.3073 - accuracy: 0.5000
Epoch 3/200
4/4 [==============================] - 0s 2ms/step - loss: 0.2933 - accuracy: 0.5000
Epoch 4/200
4/4 [==============================] - 0s 2ms/step - loss: 0.2854 - accuracy: 0.5000
Epoch 5/200
4/4 [==============================] - 0s 4ms/step - loss: 0.2773 - accuracy: 0.5000
Epoch 6/200
4/4 [==============================] - 0s 2ms/step - loss: 0.2742 - accuracy: 0.5000
Epoch 7/200
4/4 [==============================] - 0s 2ms/step - loss: 0.2712 - accuracy: 0.2500
Epoch 8/200
4/4 [==============================] - 0s 2ms/step - loss: 0.2702 - accuracy: 0.5000
Epoch 9/200
4/4 [==============================] - 0s 2ms/step - loss: 0.2688 - accuracy: 0.5000
Epoch 10/200
4/4 [==============================] - 0s 2ms/step - loss: 0.2667 - accuracy: 0.5000
Epoch 11/200
4/4 [===========

In [0]:
# 3.29 tf.keras 를 이용한 XOR 네트워크 평가
score = model.evaluate(x, y)
print(score)

1/1 [==============================] - 0s 1ms/step - loss: 0.2433 - accuracy: 0.7500
[0.24332059919834137, 0.75]


In [0]:
# 9-3 deep and wide
import tensorflow as tf
import numpy as np

x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=10, input_dim=2, activation='sigmoid'))
tf.model.add(tf.keras.layers.Dense(units=10, activation='sigmoid'))
tf.model.add(tf.keras.layers.Dense(units=10, activation='sigmoid'))
tf.model.add(tf.keras.layers.Dense(units=10, activation='sigmoid'))
tf.model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# SGD not working very well due to vanishing gradient problem, switched to Adam for now
# or you may use activation='relu', study chapter 10 to know more on vanishing gradient problem.
tf.model.compile(loss='binary_crossentropy', optimizer=tf.optimizers.Adam(lr=0.1), metrics=['accuracy'])
tf.model.summary()

history = tf.model.fit(x_data, y_data, epochs=200)

predictions = tf.model.predict(x_data)
print('Prediction: \n', predictions)


Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 10)                30        
_________________________________________________________________
dense_3 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_4 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_5 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 11        
Total params: 371
Trainable params: 371
Non-trainable params: 0
_________________________________________________________________
Epoch 1/200
1/1 [==============================] - 0s 1ms/step - loss: 0.7462 - accuracy: 0.5000
Epoch 2/200
1/1 [========

In [0]:
score = tf.model.evaluate(x_data, y_data)
print(score)

1/1 [==============================] - 0s 1ms/step - loss: 6.6972e-04 - accuracy: 1.0000
[0.0006697187782265246, 1.0]
